# This file was generated by the {rix} R package v0.17.0 on 2025-07-17
# with following call:
# >rix(r_ver = "4.4.2",
#  > r_pkgs = c("MASS",
#  > "Matrix",
#  > "R6",
#  > "RColorBrewer",
#  > "Rcpp",
#  > "Tplyr",
#  > "V8",
#  > "admiral",
#  > "admiraldev",
#  > "assertthat",
#  > "backports",
#  > "base64enc",
#  > "bit",
#  > "bit64",
#  > "broom",
#  > "bslib",
#  > "cachem",
#  > "cellranger",
#  > "checkmate",
#  > "cli",
#  > "clipr",
#  > "colorspace",
#  > "commonmark",
#  > "cowplot",
#  > "cpp11",
#  > "crayon",
#  > "curl",
#  > "data.table",
#  > "datasetjson",
#  > "diffdf",
#  > "digest",
#  > "dplyr",
#  > "emmeans",
#  > "estimability",
#  > "evaluate",
#  > "fansi",
#  > "farver",
#  > "fastmap",
#  > "fontawesome",
#  > "forcats",
#  > "formatters",
#  > "fs",
#  > "generics",
#  > "ggplot2",
#  >      "ggsurvfit",
#  > "glue",
#  > "gtable",
#  > "haven",
#  > "highr",
#  > "hms",
#  > "htmltools",
#  > "huxtable",
#  > "isoband",
#  > "janitor",
#  > "jquerylib",
#  > "jsonlite",
#  > "jsonvalidate",
#  > "knitr",
#  > "labeling",
#  > "lattice",
#  > "lifecycle",
#  > "lubridate",
#  > "magrittr",
#  > "memoise",
#  > "metacore",
#  > "metatools",
#  > "mgcv",
#  > "mime",
#  > "munsell",
#  > "mvtnorm",
#  > "nlme",
#  > "numDeriv",
#  > "patchwork",
#  > "pharmaRTF",
#  > "pillar",
#  > "pkgconfig",
#  > "prettyunits",
#  > "progress",
#  > "purrr",
#  > "r2rtf",
#  > "rappdirs",
#  > "readr",
#  > "readxl",
#  > "rematch",
#  > "renv",
#  > "rlang",
#  > "rmarkdown",
#  > "rtables",
#  > "sass",
#  > "scales",
#  >      "snakecase",
#  > "stringi",
#  > "stringr",
#  > "survival",
#  > "tibble",
#  > "tidyr",
#  > "tidyselect",
#  > "timechange",
#  > "tinytex",
#  > "tzdb",
#  > "utf8",
#  > "vctrs",
#  > "viridisLite",
#  > "vroom",
#  > "withr",
#  > "xfun",
#  > "xml2",
#  > "xportr",
#  > "yaml",
#  > "yyjsonr"),
#  > system_pkgs = c("dejavu_fonts",
#  > "quarto"),
#  > tex_pkgs = c("amsmath",
#  > "framed",
#  > "multirow",
#  > "wrapfig",
#  > "tabu",
#  > "threeparttable",
#  > "threeparttablex",
#  > "environ",
#  > "makecell",
#  > "tcolorbox",
#  > "tikzfill",
#  > "pdfcol",
#  > "fontawesome5"),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > print = TRUE)
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-02-24.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      admiral
      admiraldev
      assertthat
      backports
      base64enc
      bit
      bit64
      broom
      bslib
      cachem
      cellranger
      checkmate
      cli
      clipr
      colorspace
      commonmark
      cowplot
      cpp11
      crayon
      curl
      data_table
      datasetjson
      diffdf
      digest
      dplyr
      emmeans
      estimability
      evaluate
      fansi
      farver
      fastmap
      fontawesome
      forcats
      formatters
      fs
      generics
      ggplot2
      ggsurvfit
      glue
      gtable
      haven
      highr
      hms
      htmltools
      huxtable
      isoband
      janitor
      jquerylib
      jsonlite
      jsonvalidate
      knitr
      labeling
      lattice
      lifecycle
      lubridate
      magrittr
      MASS
      Matrix
      memoise
      metacore
      metatools
      mgcv
      mime
      munsell
      mvtnorm
      nlme
      numDeriv
      patchwork
      pharmaRTF
      pillar
      pkgconfig
      prettyunits
      progress
      purrr
      r2rtf
      R6
      rappdirs
      RColorBrewer
      Rcpp
      readr
      readxl
      rematch
      renv
      rlang
      rmarkdown
      rtables
      sass
      scales
      snakecase
      stringi
      stringr
      survival
      tibble
      tidyr
      tidyselect
      timechange
      tinytex
      Tplyr
      tzdb
      utf8
      V8
      vctrs
      viridisLite
      vroom
      withr
      xfun
      xml2
      xportr
      yaml
      yyjsonr;
  };
  
  tex = (pkgs.texlive.combine {
    inherit (pkgs.texlive) 
      scheme-small
      amsmath
      environ
      fontawesome5
      framed
      makecell
      multirow
      pdfcol
      tabu
      tcolorbox
      threeparttable
      threeparttablex
      tikzfill
      wrapfig;
  });
    
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      dejavu_fonts
      glibcLocales
      nix
      quarto
      R
      pandoc
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs tex system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
