name: QC Check ✅

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  qc-check:
    runs-on: ubuntu-latest

    steps:
    - name: Check out this repository
      uses: actions/checkout@v2

    - name: Check out CDISC_pilot_replication repository
      uses: actions/checkout@v2
      with:
        repository: atorus-research/CDISC_pilot_replication
        path: CDISC_pilot_replication

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install R dependencies
      run: |
        Rscript -e 'install.packages(c("dplyr", "jsonlite"), repos = "cran.rstudio.com")'

    - name: Run QC script
      run: Rscript qc_check.R

    - name: Upload report artifact
      uses: actions/upload-artifact@v2
      with:
        name: qc-report.html
        path: report/