
---
# reports changed files
# rds2json

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '50_automatic_convert_rds_to_json'
    paths:
      - '**/*.rds'

name: rds2json EXPERIMENTAL

concurrency:
  group: lint-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  convert_rds:
    runs-on: ubuntu-latest
    env:
         GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
#    container:
#         image:  rocker/r-ver:latest
    steps:
      - name: Check out this repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("dplyr", "datasetjson", "metacore", "tidyr"), 
          repos = "https://packagemanager.posit.co/cran/__linux__/noble/latest")'

      - name: run code rds to json
        run: |
          Rscript -e 'source("pilot5-submission/pilot5-programs/convert_rds_to_json.r")'
        shell: bash

      - name: Commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update json files" || \
            echo "no changes; nothing to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#          file-path: qc.Rmd
      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
             Hello world ! :wave:
