---
name: Check Spelling

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      r-version:
        description: 'The version of R to use'
        default: '4.4'
        required: false
        type: string
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main
      - devel


concurrency:
  group: spelling-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  roxygen:
    name: Spellcheck
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    if: >
      !contains(github.event.commits[0].message, '[skip spellcheck]')
    steps:
      ##################### BEGIN boilerplate steps #####################
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v5.4

      - name: Checkout repo (PR) 🛎
        uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ steps.branch-name.outputs.head_ref_branch }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Checkout repository
        uses: actions/checkout@v3
        if: github.event_name != 'pull_request'
        with:
          ref: ${{ steps.branch-name.outputs.head_ref_branch }}

      - name: Normalize inputs
        id: normalizer
        run: |
          R_VERSION="${{ github.event.inputs.r-version }}"
          if [ "$R_VERSION" == "" ]
          then {
            R_VERSION="4.4"
          }
          fi
          echo "::set-output name=R_VERSION::$R_VERSION"
        shell: bash

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ steps.normalizer.outputs.R_VERSION }}
          use-public-rspm: true

      - name: setup renv
        uses: r-lib/actions/setup-renv@v2
          
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/share/renv
            ~/.staged.dependencies
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: ${{ runner.os }}-renv-
          
      - name: Install Dependencies
        run: |
          renv::install("spelling")
        shell: Rscript {0}

      ########## Run spellcheck on directory of R scripts ##########
      - name: Run Spellcheck
        run: |
          input_files <- list.files("pilot5-submission/pilot5-programs", pattern = "\\.(r|Rmd)$", full.names = TRUE)
          (spell_errors <- spelling::spell_check_files(input_files))
          if (nrow(spell_errors) > 0L) {
            quit(save = "no", status = 1, runLast = FALSE)
          }
        shell: Rscript {0}
