
name: QC TLF Check ✅

on:
  pull_request:
    branches:
      - main

jobs:
  qc-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repository
        uses: actions/checkout@v4
    
      - name: Check out CDISC_pilot_replication repository
        uses: actions/checkout@v4
        with:
          repository: RConsortium/submissions-pilot3-adam
          sparse-checkout: 'submission/adam'
          path: submissions-pilot3-adam
    
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Linux Deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev imagemagick libmagick++-dev libreoffice 
    
      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("waldo", "ellmer", "stringr", "quarto", "magick"), repos = "https://packagemanager.posit.co/cran/__linux__/noble/latest")'
          
      - name: Run QC script
        run: R -e 'quarto::quarto_render("tlf-qc.qmd")'
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: output qc-tlf.Rmd
        run: cat qc-tlf.Rmd
        if: always()
    
      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: tlc-qc.html
          path: tlc-qc.html
          
      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: qc-tlf.Rmd
          